=== teco-kit/ModelDrivenGateways/bundles/DataModeling/src/edu.teco.automata.generator/src/prs74.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.teco.edu/SensorValuesSchema" elementFormDefault="qualified" targetNamespace="http://www.teco.edu/SensorValuesSchema">
    <complexType name="GravityType">
      <sequence>
         <element name="AcclValue" type="short"/>
         <element name="AcclIdx" type="unsignedByte"/>
      </sequence>
    </complexType>
    <complexType name="LightType">
      <sequence>
         <element name="LightValue" type="unsignedByte"/>
         <element name="LightIdx" type="unsignedByte"/>
      </sequence>
    </complexType>
    <complexType name="ForceType">
      <sequence>
         <element name="ForceValue" type="unsignedByte"/>
         <element name="ForceIdx" type="unsignedByte"/>
      </sequence>
    </complexType>
    <complexType name="TempType">
      <sequence>
         <element name="TempValue" type="byte"/>
         <element name="TempIdx" type="unsignedByte"/>
      </sequence>
    </complexType>
    <complexType name="SensorValuesType">
      <sequence>
         <element maxOccurs="1" minOccurs="0" name="AcclX" type="tns:GravityType"/>
         <element maxOccurs="1" minOccurs="0" name="AcclY" type="tns:GravityType"/>
         <element maxOccurs="1" minOccurs="0" name="AcclZ" type="tns:GravityType"/>
         <element maxOccurs="1" minOccurs="0" name="Audio" type="unsignedByte"/>
         <element maxOccurs="1" minOccurs="0" name="Light" type="tns:LightType"/>
         <element maxOccurs="1" minOccurs="0" name="AmbientLight" type="tns:LightType"/>
         <element maxOccurs="1" minOccurs="0" name="Force" type="tns:ForceType"/>  
         <element maxOccurs="1" minOccurs="0" name="Temperature" type="tns:TempType"/>
         <element maxOccurs="1" minOccurs="0" name="Voltage" type="unsignedShort"/>
      </sequence>
    </complexType>
    <element name="SensorValues" type="tns:SensorValuesType"/>
</schema>

=== teco-kit/ModelDrivenGateways/bundles/DataModeling/trunk/src/edu.teco.automata.generator/src/edu/teco/automata/generator/test/xsd/prs74.xml
<SensorValues xmlns="http://www.teco.edu/SensorValuesSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.teco.edu/SensorValuesSchema prs74.xsd ">
	<AcclX>
		<AcclValue>300</AcclValue>
		<AcclIdx>0</AcclIdx>
	</AcclX>
	<AcclY>
      <AcclValue>300</AcclValue>
      <AcclIdx>0</AcclIdx>
   </AcclY>
   <AcclZ>
      <AcclValue>300</AcclValue>
      <AcclIdx>0</AcclIdx>
   </AcclZ>
   <Temperature>
   	<TempValue>4</TempValue>
   	<TempIdx>0</TempIdx>
   </Temperature>
   <Voltage>3400</Voltage>
</SensorValues>

=== teco-kit/ModelDrivenGateways/bundles/DataModeling/trunk/src/edu.teco.automata.generator/src/edu/teco/automata/generator/test/prs741.xml
<?xml version="1.0" encoding="UTF-8"?>
<SensorValues xmlns="http://www.teco.edu/SensorValuesSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.teco.edu/SensorValuesSchema prs74.xsd ">
  <AcclX>
    <AcclValue>0</AcclValue>
    <AcclIdx>0</AcclIdx>
  </AcclX>
  <AcclY>
    <AcclValue>0</AcclValue>
    <AcclIdx>0</AcclIdx>
  </AcclY>
  <AcclZ>
    <AcclValue>0</AcclValue>
    <AcclIdx>0</AcclIdx>
  </AcclZ>
  <Audio>0</Audio>
  <Light>
    <LightValue>0</LightValue>
    <LightIdx>0</LightIdx>
  </Light>
  <AmbientLight>
    <LightValue>0</LightValue>
    <LightIdx>0</LightIdx>
  </AmbientLight>
  <Force>
    <ForceValue>0</ForceValue>
    <ForceIdx>0</ForceIdx>
  </Force>
  <Temperature>
    <TempValue>0</TempValue>
    <TempIdx>0</TempIdx>
  </Temperature>
  <Voltage>0</Voltage>
</SensorValues>
