=== teco-kit/ModelDrivenGateways/bundles/DataModeling/trunk/src/edu.teco.automata.generator/src/edu/teco/automata/generator/test/xsd/config.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
		<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.teco.edu/SSimp"
			elementFormDefault="qualified" targetNamespace="http://www.teco.edu/SSimp">		
			
			<complexType name="SensorConfigurationType">
				<sequence>
					<element name="sensors" type="tns:SensorSelectionType" />
				</sequence>
			</complexType>
			
			<complexType name="GravitySensorConfigType">
			</complexType>
			
			<complexType name="LightSensorConfigType">
			</complexType>
			
			<complexType name="ForceSensorConfigType">
			</complexType>
			
			<complexType name="TempSensorConfigType">
			</complexType>
			
			<complexType name="AudioSensorConfigType">
			</complexType>
			

			<complexType name="SensorSelectionType">
				<sequence>
					<element maxOccurs="1" minOccurs="0" name="AcclX" type="tns:GravitySensorConfigType" />
					<element maxOccurs="1" minOccurs="0" name="AcclY" type="tns:GravitySensorConfigType" />
					<element maxOccurs="1" minOccurs="0" name="AcclZ" type="tns:GravitySensorConfigType" />
					<element maxOccurs="1" minOccurs="0" name="Audio" type="tns:AudioSensorConfigType" />
					<element maxOccurs="1" minOccurs="0" name="Light" type="tns:LightSensorConfigType" />
					<element maxOccurs="1" minOccurs="0" name="AmbientLight"	type="tns:LightSensorConfigType" />
					<element maxOccurs="1" minOccurs="0" name="Force" type="tns:ForceSensorConfigType" />
					<element maxOccurs="1" minOccurs="0" name="Temperature"		type="tns:TempSensorConfigType" />
					<element maxOccurs="1" minOccurs="0" name="Voltage" type="tns:ForceSensorConfigType" />
				</sequence>
			</complexType>
			
			<element name="SensorConfiguration" type="tns:SensorConfigurationType" />		
		   
        </schema>

=== teco-kit/ModelDrivenGateways/bundles/DataModeling/trunk/src/edu.teco.automata.generator/src/edu/teco/automata/generator/test/xsd/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:SensorConfiguration xmlns:tns="http://www.teco.edu/SSimp" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.teco.edu/SSimp config.xsd ">
  <tns:sensors>
    <tns:AcclX/>
    <tns:AcclY/>
    <tns:AcclZ/>
    <tns:Audio/>
    <tns:Light/>
    <tns:Force/>
    <tns:Voltage/>
  </tns:sensors>
</tns:SensorConfiguration>
